### ISSUE TITLE
Transpose does not work

### ISSUE THREAD

**Issue by cpede** [amroamroamro/prettify-matlab#4]
When using quote as transpose method, it is believed to be a string.

As in your own example:
```
M = rand(3,3)';
N = rand(5,5)';
```
https://jsfiddle.net/cpede/xj8o8qan/

-cpede

**Comment by amroamroamro** [comment]
Your snippet is not correct, try this instead:

```html
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js?lang=matlab"></script>

<pre class="prettyprint lang-matlab">
% transpose test
M = rand(3,3)';
N = rand(5,5)';
</pre>
```

Two things to note:
- MATLAB is implemented as an extension, so you must tell the auto-loader script to load its language handler (read the [docs](https://github.com/google/code-prettify/blob/master/docs/getting_started.md#auto-loader)).
- the class name is `lang-matlab` not `lang_matlab`
